<div class="container">
    <div id="carouselSlides" class="carousel slide mt-5" data-bs-ride="carousel">
        <div class="carousel-inner py-5">
            <div class="carousel-item active">
                <img src="<?= base_path('/img/slide-1.png') ?>" class="d-block w-100" alt="slide-1">
            </div>
            <div class="carousel-item">
                <img src="<?= base_path('/img/slide-2.png') ?>" class="d-block w-100" alt="slide-2">
            </div>
            <div class="carousel-item">
                <img src="<?= base_path('/img/slide-3.png') ?>" class="d-block w-100" alt="slide-3">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselSlides" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselSlides" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
    <div class="title-box mb-3">
        <div class="container py-2">
            <h1 class="display-6">SPEKTRAL</h1>
        </div>
    </div>
    <div class="row mb-2">
        <p style="text-align:justify;">Sistem Pembinaan Statistik Sektoral (SPEKTRAL) merupakan suatu alat bantu yang bertujuan untuk mewujudkan kolaborasi pembinaan statistik sektoral kepada Sumber Daya Manusia (SDM) yang ada di masing-masing Organisasi Perangkat Daerah (OPD).</p>
        <p style="text-align:justify;">SPEKTRAL mempermudah Instansi atau OPD di pemerintahan daerah untuk mengakses layanan statistik baik berupa Permintaan Pembinaan Statistik, Pelaporan Metadata Statistik, maupun Pengajuan Rekomendasi Statistik. SPEKTRAL juga menyediakan modul pembinaan statistik dan literasi statistik yang dapat diakses dengan mudah kapan dan dimana saja.</p>
    </div>
    <div class="title-box mb-3">
        <div class="container py-2">
            <h1 class="display-6">LAYANAN INSTANSI</h1>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col-4 d-flex align-items-center justify-content-center">
            <a class="btn btn-outline-primary rounded-pill py-2 px-5 text-uppercase fw-semibold small" href="<?= route(App\Enums\ResourceEnum::PERMINTAAN_PEMBINAAN_LIST) ?>">Permintaan Pembinaan Statistik</a>
        </div>
        <div class="col-4 d-flex align-items-center justify-content-center">
            <a class="btn btn-outline-info rounded-pill py-2 px-5 text-uppercase fw-semibold small" href="<?= route(App\Enums\ResourceEnum::ROMANTIK) ?>">Pengajuan Rekomendasi Statistik</a>
        </div>
        <div class="col-4 d-flex align-items-center justify-content-center">
            <a class="btn btn-outline-warning rounded-pill py-2 px-5 text-uppercase fw-semibold small" href="<?= route(App\Enums\ResourceEnum::METADATA) ?>">Pelaporan Metadata Statistik</a>
        </div>
    </div>
    <div class="title-box mb-3">
        <div class="container py-2">
            <h1 class="display-6">MODUL PEMBINAAN STATISTIK</h1>
        </div>
    </div>
    <p style="text-align:justify;">Badan Pusat Statistik (BPS) sebagai Pembina Data Statistik berupaya untuk menyediakan instrumen guna mengakselerasi tingkat kematangan penyelenggaraan statistik sektoral di pemerintahan daerah salah satunya dengan menyediakan modul-modul pembinaan statistik yang dikelompokkan dalam kategori EPSS - Satu Data Indonesia (SDI), EPSS - Kualitas Data, EPSS - Proses Bisnis Statistik, EPSS - Kelembagaan, EPSS - Sistem Statistik Nasional (SSN), Desa/Kelurahan Cinta Statistik, dan Umum dan Peraturan.
    </p>
    <div class="row mb-2">
        <?php
 foreach ($kategori_pembinaan as $cat) { ?>
            <div class="col-lg-6 col-md-12 mb-2">
                <div class="card">
                    <div class="card-body">
                        <img class="img-thumbnail float-start" src="<?= site_url('/img/list.png') ?>" alt="" style="padding:10px; margin-right:10px;background-color:#567189;">
                        <div class="py-1"><a class="link-primary link-underline-opacity-0" href="<?= route(App\Enums\ResourceEnum::MODUL_PEMBINAAN_LIST, "/{$cat['id']}") ?>"><span class="fs-5"><?= $cat['nama'] ?></span></a></div>
                        <br>
                        <p class="float-start" style="text-align:justify;"><?= $cat['deskripsi'] ?></p>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
    <div class="title-box mb-3">
        <div class="container py-2">
            <h1 class="display-6">MODUL LITERASI STATISTIK</h1>
        </div>
    </div>
    <p style="text-align:justify;">Badan Pusat Statistik (BPS) sebagai Pembina Data Statistik berupaya untuk meningkatkan pemahaman baik kepada intansi pemerintahan daerah atau OPD dan masyarakat terkait dengan statistik baik kegiatannya maupun produk statistik yang dihasilkan.
    </p>
    <div class="row mb-5">
        <?php foreach ($kategori_literasi as $cat) { ?>
            <div class="col-lg-6 col-md-12 mb-2">
                <div class="card">
                    <div class="card-body">
                        <img class="img-thumbnail float-start" src="<?= site_url('/img/list.png') ?>" alt="" style="padding:10px; margin-right:10px;background-color:#567189;">
                        <div class="py-1"><a class="link-primary link-underline-opacity-0" href="<?= route(App\Enums\ResourceEnum::MODUL_LITERASI_LIST, "/{$cat['id']}") ?>"><span class="fs-5"><?= $cat['nama'] ?></span></a></div>
                        <br>
                        <p class="float-start" style="text-align:justify;"><?= $cat['deskripsi'] ?></p>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>