<?= $this->render('frontend/components/titlebox') ?>
<div class="container mb-5">
    <div class="row d-flex justify-content-center">
        <div class="col-lg-4 col-md-6">
            <div>
                <?php $form = form($model); ?>
                <?= $form->begin(route(App\Enums\ResourceEnum::DO_RESET_PASSWORD, $token), Faster\Component\Enums\HttpMethodEnum::POST, ['class' => 'needs-validation', 'autocomplete' => 'off']) ?>
                <div class="row mb-2">
                    <div class="form-group">
                        <label for="id_password" class="form-label text-muted"><?= $model->getLabel('password') ?><span class="text-danger">*</span></label>
                        <?= $form->field('password', ['class' => 'form-control', 'required',  'id' => 'id_password'])->passField() ?>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="form-group">
                        <label for="id_repassword" class="form-label text-muted"><?= $model->getLabel('repassword') ?><span class="text-danger">*</span></label>
                        <?= $form->field('repassword', ['class' => 'form-control', 'required',  'id' => 'id_repassword'])->passField() ?>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="form-group">
                        <label for="id_captcha" class="form-label text-muted"><?= $model->getLabel('captcha') ?><span class="text-danger">*</span></label>
                        <?= $form->captcha() ?>
                        <?= $form->field('captcha', ['class' => 'form-control', 'required', 'id' => 'id_captcha']) ?>
                    </div>
                </div>
                <div class="form-text mb-5">Keterangan: <span class="text-danger">*</span> Wajib diisi.</div>
                <div class="row">
                    <div>
                        <input class="btn btn-primary rounded-pill py-2 px-5" type="submit" name="submit" value="Simpan" />
                    </div>
                </div>
                <?= $form->end() ?>
            </div>
        </div>
    </div>
</div>