<?= $this->render('frontend/components/titlebox') ?>
<div class="container mb-5">
    <div class="row d-flex justify-content-center">
        <div class="col-lg-4 col-md-6">
            <div>
                <?php $form = form($model); ?>
                <?= $form->begin(route(App\Enums\ResourceEnum::RESET_PASSWORD), Faster\Component\Enums\HttpMethodEnum::POST, ['class' => 'needs-validation', 'autocomplete' => 'off']) ?>
                <div class="row mb-2">
                    <div class="form-group">
                        <label for="id_email" class="form-label text-muted"><?= $model->getLabel('email') ?><span class="text-danger">*</span></label>
                        <?= $form->field('email', ['class' => 'form-control', 'required', 'autofocus', 'id' => 'id_email'])->emailField() ?>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="form-group">
                        <label for="id_captcha" class="form-label text-muted"><?= $model->getLabel('captcha') ?><span class="text-danger">*</span></label>
                        <?= $form->captcha() ?>
                        <?= $form->field('captcha', ['class' => 'form-control', 'required', 'id' => 'id_captcha']) ?>
                    </div>
                </div>
                <div class="form-text mb-5">Keterangan: <span class="text-danger">*</span> Wajib diisi.</div>
                <div class="row mb-5 text-center">
                    <div>
                        <input class="btn btn-primary rounded-pill py-2 px-5" type="submit" name="submit" value="Reset" />
                    </div>
                </div>
                <?= $form->end() ?>
                <div class="row text-center">
                    <span class="text-muted">Sudah ingat password?<a class="btn btn-outline-success rounded-pill px-3 ms-2" href="<?= route(App\Enums\ResourceEnum::LOGIN) ?>">Login</a></span>
                </div>
            </div>
        </div>
    </div>
</div>