<?= $this->render('frontend/components/titlebox') ?>
<div class="container mb-5">
    <div class="row">
        <div class="col-lg-12 mb-2">
            <p style="text-align: justify;">Undang-Undang Nomor 16 Tahun 1997 tentang Statistik mengamanatkan BPS sebagai lembaga yang bertugas dan bertanggung jawab terhadap penyelenggaraan statistik di Indonesia. Dalam hal ini, BPS bekerja sama dengan instansi pemerintah dan unsur masyarakat guna mengembangkan Sistem Statistik Nasional (SSN), mendukung pembangunan nasional, dan meningkatkan kontribusi dan apresiasi masyarakat terhadap statistik.</p>
            </p>
            <p style="text-align: justify;">Dalam rangka melaksanakan amanat Undang-Undang tersebut, ditetapkanlah Peraturan Pemerintah Nomor 51 Tahun 1999 tentang Penyelenggaraan Statistik yang salah satu poinnya menjelaskan bahwa penyelenggara kegiatan statistik sektoral wajib:</p>
            <ol>
                    <li>memberitahukan rencana penyelenggaraan kegiatan statistik sektoral kepada BPS;</li>
                    <li>mengikuti rekomendasi kegiatan statistik yang diberikan BPS; dan</li>
                    <li>menyerahkan hasil penyelenggaraan kegiatan statistik sektoral yang dilakukannya kepada BPS.</li>
            </ol>
            <p style="text-align: justify;">Hal ini selaras dengan Peraturan Pemerintah Nomor 18 Tahun 2016 tentang Perangkat Daerah yang menyatakan bahwa indikator penting untuk mengukur pemetaan intensitas urusan pemerintahan dan penentuan beban kerja perangkat daerah urusan pemerintahan bidang statistik adalah ”Jumlah survei dan kompilasi produk administrasi bidang sosial, ekonomi, politik, hukum dan HAM yang mendapatkan rekomendasi BPS”.</p>
            <p style="text-align: justify;">Kewajiban-kewajiban tersebut kemudian diselenggarakan dalam suatu mekanisme pemberian rekomendasi kegiatan statistik. Mekanisme tersebut bertujuan untuk menghindari duplikasi penyelenggaraan kegiatan statistik sektoral, mendorong perolehan hasil yang dapat dipertanggungjawabkan secara teknis, serta mengurangi keraguan konsumen data atas beberapa sajian data atau indikator yang sama tetapi nilainya berbeda.</p>
            <p style="text-align: justify;">Perwujudan koordinasi yang baik antara penyelenggara kegiatan statistik sektoral dan BPS dalam mekanisme pemberian rekomendasi kegiatan statistik akan meningkatkan kualitas penyelenggaraan kegiatan statistik sektoral. Dengan demikian, kegiatan statistik sektoral tersebut dapat menghasilkan output yang berkualitas. Selain itu, peran aktif instansi pemerintah dalam menyampaikan rancangan dan mengajukan rekomendasi kegiatan statistik kepada BPS dapat turut mewujudkan SSN yang andal, efektif, dan efisien.</p>
            <p class="text-center mt-5"><a href="https://romantik.web.bps.go.id/" target="_blank" class="btn btn-success rounded-pill py-2 px-5">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                        <path transform="rotate(0,8,8) translate(2.38418749631819E-06,0) scale(0.500000357628124,0.500000357628124)" d="M18.285034,0L32,13.71497 18.285034,27.43 18.285034,17.729008 0,17.729008 0,8.5849627 18.285034,8.5849627z" />
                    </svg> Ajukan Romantik</a>
            </p>
        </div>
    </div>
</div>