<?= $this->render('frontend/components/titlebox') ?>
<div class="container mb-5">
    <div class="row mb-2">
        <div class="col-lg-6">
            <span class="text-muted"><?= $model->getLabel('nama') ?></span>
            <div><?= $row['nama'] ?></div>
        </div>
        <div class="col-lg-6">
            <span class="text-muted"><?= $model->getLabel('nip') ?></span>
            <div><?= $row['nip'] ?></div>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-lg-6">
            <span class="text-muted"><?= $model->getLabel('email') ?></span>
            <div><?= $row['email'] ?></div>
        </div>
        <div class="col-lg-6">
            <span class="text-muted"><?= $model->getLabel('nomor_wa') ?></span>
            <div><?= $row['nomor_wa'] ?></div>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-lg-6">
            <span class="text-muted"><?= $model->getLabel('instansi') ?></span>
            <div><?= $row['instansi'] ?></div>
        </div>
        <div class="col-lg-6">
            <span class="text-muted"><?= $model->getLabel('tingkat') ?></span>
            <div><?= $row['tingkat_instansi'] ?></div>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-lg-6">
            <span class="text-muted"><?= $model->getLabel('jabatan') ?></span>
            <div><?= $row['jabatan'] ?></div>
        </div>
    </div>
    <hr class="my-2" style="border: 1px solid silver;" />
    <div class="row">
        <div class="d-flex justify-content-center">
            <a class="btn btn-primary rounded-pill py-2 px-5" href="<?= route(App\Enums\ResourceEnum::USER_UPDATE) ?>">Ubah Data</a>
        </div>
    </div>
</div>