<div class="container">
    <div class="row mb-5">
        <h2 class="text-primary py-3">SELAMAT DATANG DI SPEKTRAL BACKEND</h2>
        <div class="row mb-4">
            <div class="col-4">
                <div class="card">
                    <div class="card-body d-flex align-items-center">
                        <div class="me-3 text-white bg-primary p-3">
                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" viewBox="0 0 16 16">
                                <path transform="rotate(0,8,8) translate(2.38418749631819E-06,0) scale(0.500000357628124,0.500000357628124)" d="M8.3560181,18.363037C10.371002,19.880005 12.873993,20.779053 15.584991,20.779053 18.295013,20.779053 20.799011,19.880005 22.813995,18.363037 27.524017,18.955994 31.167999,22.973022 31.167999,27.843994L31.167999,32 0,32 0,27.843994C0,22.973022,3.6459961,18.955994,8.3560181,18.363037z M15.584991,0C20.403992,0 24.311005,3.90802 24.311005,8.7280273 24.311005,13.548035 20.403992,17.454041 15.584991,17.454041 10.765015,17.454041 6.8580017,13.548035 6.8580017,8.7280273 6.8580017,3.90802 10.765015,0 15.584991,0z" />
                            </svg>
                        </div>
                        <div>
                            <div class="fs-6 fw-semibold text-primary">
                                <div class="d-flex flex-column"><span class="text-secondary" style="font-size: 10pt;"><?= $pengguna['aktif'] ?> Pengguna Aktif</span><span class="text-dark" style="font-size: 10pt;"><?= $pengguna['tidak_aktif'] ?> Pengguna Tidak Aktif</span></div>
                            </div>
                            <div class="text-medium-emphasis text-uppercase fw-semibold small"><span class="text-primary"><?= $pengguna['aktif'] + $pengguna['tidak_aktif'] ?> Total Pengguna</span></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card">
                    <div class="card-body d-flex align-items-center">
                        <div class="me-3 text-white bg-info p-3">
                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" viewBox="0 0 16 16">
                                <path transform="rotate(0,8,8) translate(2.38418749631819E-06,0) scale(0.500000357628124,0.500000357628124)" d="M8.3560181,18.363037C10.371002,19.880005 12.873993,20.779053 15.584991,20.779053 18.295013,20.779053 20.799011,19.880005 22.813995,18.363037 27.524017,18.955994 31.167999,22.973022 31.167999,27.843994L31.167999,32 0,32 0,27.843994C0,22.973022,3.6459961,18.955994,8.3560181,18.363037z M15.584991,0C20.403992,0 24.311005,3.90802 24.311005,8.7280273 24.311005,13.548035 20.403992,17.454041 15.584991,17.454041 10.765015,17.454041 6.8580017,13.548035 6.8580017,8.7280273 6.8580017,3.90802 10.765015,0 15.584991,0z" />
                            </svg>
                        </div>
                        <div>
                            <div class="fs-6 fw-semibold text-info">
                                <div class="d-flex flex-column"><span class="text-secondary" style="font-size: 10pt;"><?= $modul_pembinaan['aktif'] ?> Modul Pembinaan Aktif</span><span class="text-dark" style="font-size: 10pt;"><?= $modul_pembinaan['tidak_aktif'] ?> Modul Pembinaan Tidak Aktif</span></div>
                            </div>
                            <div class="text-medium-emphasis text-uppercase fw-semibold small"><span class="text-info"><?= $modul_pembinaan['aktif'] + $modul_pembinaan['tidak_aktif'] ?> Total Modul Pembinaan</span></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card">
                    <div class="card-body d-flex align-items-center">
                        <div class="me-3 text-white bg-warning p-3"><svg xmlns="http://www.w3.org/2000/svg" class="icon icon-xl" viewBox="0 0 512 512" role="img">undefined<path fill="var(--ci-primary-color, currentColor)" d="M411.6,343.656l-72.823-47.334,27.455-50.334A80.23,80.23,0,0,0,376,207.681V128a112,112,0,0,0-224,0v79.681a80.236,80.236,0,0,0,9.768,38.308l27.455,50.333L116.4,343.656A79.725,79.725,0,0,0,80,410.732V496H448V410.732A79.727,79.727,0,0,0,411.6,343.656ZM416,464H112V410.732a47.836,47.836,0,0,1,21.841-40.246l97.66-63.479-41.64-76.341A48.146,48.146,0,0,1,184,207.681V128a80,80,0,0,1,160,0v79.681a48.146,48.146,0,0,1-5.861,22.985L296.5,307.007l97.662,63.479h0A47.836,47.836,0,0,1,416,410.732Z" class="ci-primary"></path></svg></div>
                        <div>
                            <div class="fs-6 fw-semibold text-warning">
                                <div class="d-flex flex-column"><span class="text-secondary" style="font-size: 10pt;"><?= $modul_literasi['aktif'] ?> Modul Literasi Aktif</span><span class="text-dark" style="font-size: 10pt;"><?= $modul_literasi['tidak_aktif'] ?> Modul Literasi Tidak Aktif</span></div>
                            </div>
                            <div class="text-medium-emphasis text-uppercase fw-semibold small"><span class="text-warning"><?= $modul_literasi['aktif'] + $modul_literasi['tidak_aktif'] ?> Total Modul Literasi</span></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>