<?= $this->render('frontend/components/titlebox') ?>
<div class="container mb-5">
    <div class="card">
        <?php
        $form = form($model); ?>
        <?= $form->begin($model->isEdit() ? route(App\Enums\ResourceEnum::ADMIN_MODUL_LITERASI_EDIT, strval($row['id'])) : route(App\Enums\ResourceEnum::ADMIN_MODUL_LITERASI_ENTRY), Faster\Component\Enums\HttpMethodEnum::POST, ['enctype' => 'multipart/form-data','class' => 'needs-validation', 'autocomplete' => 'off']) ?>
        <div class="card-header bg-white text-center">
            <span class="text-dark fs-4">FORMULIR</span>
        </div>
        <div class="card-body bg-white">
            <div class="row mb-2">
                <div class="col">
                    <label for="id_nama" class="form-label text-muted"><?= $model->getLabel('nama') ?><span class="text-danger">*</span></label>
                    <?= $form->field('nama', ['class' => 'form-control', 'required', 'autofocus', 'id' => 'id_nama']) ?>
                </div>
            </div>
            <div class="row mb-2">
                <div class="col">
                    <label for="id_deskripsi" class="form-label text-muted"><?= $model->getLabel('deskripsi') ?><span class="text-danger">*</span></label>
                    <?= $form->textArea('deskripsi', ['class' => 'form-control', 'required', 'id' => 'id_deskripsi','style'=>'height:100px;']) ?>
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-lg-6">
                    <label for="id_kategori" class="form-label text-muted"><?= $model->getLabel('kategori') ?><span class="text-danger">*</span></label>
                    <?= $form->select('kategori', $labels, $values,  ['class' => 'form-select', 'required', 'id' => 'id_kategori']) ?>
                </div>
                <div class="col-lg-6">
                    <span class="text-muted mb-2"><?= $model->getLabel('is_active') ?><span class="text-danger">*</span></span>
                    <div class="form-check form-switch">
                        <input class="form-check-input" type="checkbox" id="id_is_active" name="is_active" <?= $model->is_active == 1 ? 'value="1" checked' : '' ?>>
                        <label class="form-check-label" for="id_is_active">Aktif</label>
                    </div>
                </div>
            </div>
            <div class="row mb-2">
                <div class="col">
                    <?php if ($model->isEdit()) { ?>
                        <label class="form-label text-muted" for="link"><?= $model->getLabel('link') ?>:
                            <a class="ms-2" target="_blank" href="<?= site_url(app_config(App\Enums\PathEnum::MODUL_LITERASI)  . '/' . $model->link) ?>"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                                    <path transform="rotate(0,8,8) translate(2.38418749631819E-06,0) scale(0.500000357628124,0.500000357628124)" d="M15.199951,5.7999878L21.5,5.7999878 21.5,32 3.5,32C8.3999634,30.100006,14.599976,27,15,24.100006L15,23.899994 15.199951,23.899994z M0,5.7999878L0.099975586,5.7999878 4.5999756,5.7999878 4.6999512,19.399994C4.6999512,19.399994 10.599976,21 11,23.799988 11.399963,26.299988 4.5999756,29 0,30.100006z M6.8999634,0C10.5,0.70001221,12.699951,3.6000061,13.099976,4.2000122L13.099976,22.5C12,18.100006,7,17.899994,7,17.899994z" />
                                </svg></a></label>
                        <?= $form->file('link', ['class' => 'form-control', 'accept' => 'application/pdf']) ?>
                    <?php } else { ?>
                        <label class="form-label text-muted" for="link"><?= $model->getLabel('link') ?><span class="text-danger">*</span></label>
                        <?= $form->file('link', ['class' => 'form-control', 'required', 'accept' => 'application/pdf']) ?>
                    <?php } ?>
                    <div class="form-text">File modul yang diperkenankan adalah format pdf.</div>
                </div>
            </div>

            <div class="form-text">Keterangan: <span class="text-danger">*</span> Wajib diisi.</div>
        </div>
        <div class="card-footer">
            <div class="d-flex justify-content-center">
                <a href="<?= route(App\Enums\ResourceEnum::ADMIN_MODUL_LITERASI_LIST) ?>" class="btn btn-secondary rounded-pill py-2 px-5 me-2">Kembali</a>
                <input class="btn btn-primary rounded-pill py-2 px-5" type="submit" name="submit" value="Simpan" />
            </div>
        </div>
        <?= $form->end() ?>
    </div>
</div>